<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="11" passed="8" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-26T20:56:18 WIB" name="Surefire suite" finished-at="2024-11-26T20:56:20 WIB" duration-ms="1710">
    <groups>
    </groups>
    <test started-at="2024-11-26T20:56:18 WIB" name="Surefire test" finished-at="2024-11-26T20:56:20 WIB" duration-ms="1710">
      <class name="scenario.RestAssuredTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:scenario.RestAssuredTest@6cf0e0ba]" started-at="2024-11-26T20:56:18 WIB" name="setUp" finished-at="2024-11-26T20:56:18 WIB" duration-ms="257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="AddObject(java.lang.String,int,double,java.lang.String,java.lang.String)[pri:0, instance:scenario.RestAssuredTest@6cf0e0ba]" started-at="2024-11-26T20:56:18 WIB" name="AddObject" data-provider="addObject" finished-at="2024-11-26T20:56:19 WIB" duration-ms="632" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Apple MacBook Pro 16]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2019]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[19000]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Intel Core i9]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[1 TB]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddObject -->
        <test-method signature="GetAllObjects()[pri:0, instance:scenario.RestAssuredTest@6cf0e0ba]" started-at="2024-11-26T20:56:19 WIB" name="GetAllObjects" finished-at="2024-11-26T20:56:19 WIB" duration-ms="187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetAllObjects -->
        <test-method signature="UpdateObject(java.lang.String,int,double,java.lang.String,java.lang.String)[pri:1, instance:scenario.RestAssuredTest@6cf0e0ba]" started-at="2024-11-26T20:56:19 WIB" name="UpdateObject" data-provider="updateObject" finished-at="2024-11-26T20:56:19 WIB" depends-on-methods="scenario.RestAssuredTest.AddObject" duration-ms="173" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Apple MacBook Pro 17]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2020]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5000]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Intel Core i5]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[3 TB]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateObject -->
        <test-method signature="DeleteDataObject()[pri:2, instance:scenario.RestAssuredTest@6cf0e0ba]" started-at="2024-11-26T20:56:19 WIB" name="DeleteDataObject" finished-at="2024-11-26T20:56:19 WIB" depends-on-methods="scenario.RestAssuredTest.AddObject" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteDataObject -->
        <test-method signature="GetAllObjectsByIds()[pri:3, instance:scenario.RestAssuredTest@6cf0e0ba]" started-at="2024-11-26T20:56:19 WIB" name="GetAllObjectsByIds" finished-at="2024-11-26T20:56:20 WIB" depends-on-methods="scenario.RestAssuredTest.DeleteDataObject" duration-ms="201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetAllObjectsByIds -->
      </class> <!-- scenario.RestAssuredTest -->
      <class name="ParallelTest">
        <test-method signature="testMethod1()[pri:0, instance:ParallelTest@9f116cc]" started-at="2024-11-26T20:56:18 WIB" name="testMethod1" finished-at="2024-11-26T20:56:18 WIB" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method signature="testMethod2()[pri:0, instance:ParallelTest@9f116cc]" started-at="2024-11-26T20:56:18 WIB" name="testMethod2" finished-at="2024-11-26T20:56:18 WIB" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method retried="true" signature="testRetry()[pri:0, instance:ParallelTest@9f116cc]" started-at="2024-11-26T20:56:18 WIB" name="testRetry" finished-at="2024-11-26T20:56:18 WIB" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at ParallelTest.testRetry(ParallelTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRetry -->
        <test-method signature="testRetry()[pri:0, instance:ParallelTest@9f116cc]" started-at="2024-11-26T20:56:18 WIB" name="testRetry" finished-at="2024-11-26T20:56:18 WIB" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at ParallelTest.testRetry(ParallelTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRetry -->
        <test-method signature="testMethod3()[pri:0, instance:ParallelTest@9f116cc]" started-at="2024-11-26T20:56:18 WIB" name="testMethod3" finished-at="2024-11-26T20:56:18 WIB" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
        <test-method retried="true" signature="testRetry()[pri:0, instance:ParallelTest@9f116cc]" started-at="2024-11-26T20:56:18 WIB" name="testRetry" finished-at="2024-11-26T20:56:18 WIB" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at ParallelTest.testRetry(ParallelTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRetry -->
      </class> <!-- ParallelTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
